### ISSUE TITLE
Update to latest foundry version

### ISSUE THREAD

**Issue by Ekster-powerplay** [qrizzl/ed4-steps2foundry#4]
Hello,

Would it be possible to update this module to the latest foundry version? The current version does not work properly.

Thank you!

**Comment by qrizzl** [comment]
Hi there,
could you provide some more information on what exactly doesnt work? A verbal description and/or console output would be helpful.

Thank you!

**Comment by Ekster-powerplay** [comment]
Hey thanks for the reply!

I get a bunch of errors, pasted the blurb from log below.

I'm trying to import a freshly made .json (from the latest stable web version of steps) into Eartdawn 0.8.0 and Foundry Version 10 - Build 291. It creates the actor but aside from the player name it is almost empty and throws an error.

Seems to me that a bunch of dependencies have changed or moved.

Also I noticed that in the FASA modules an "adventurers's kit" is named "Adventuring Kit"  or  "Adventuring Kit (with Tent)"

The Shaman token missing is a bug from the fasa module, is already known.

Hope this helps ;)

Bruno

`
commons.js:1703 Error: You are accessing the earthdawn4eActor#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eActor._logV10CompatibilityWarning (commons.js:6642:14)
    at get data [as data] (commons.js:6542:24)
    at earthdawn4eActor._preCreate (earthdawn-4e-Actor.js:19:10)
    at async ClientDatabaseBackend._preCreateDocumentArray (foundry.js:12530:7)
    at async ClientDatabaseBackend._createDocuments (foundry.js:12459:22)
    at async Actor.createDocuments (commons.js:6110:23)
    at async Actor.create (commons.js:6233:23)
    at async Steps2Foundry._import (main.js:217:26)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:6946 Foundry VTT | Created Actor with id [GqqJiMadV2FwBP92]
token-shamane.webp:1          Failed to load resource: the server responded with a status of 404 (Not Found)
commons.js:6946 Foundry VTT | Created Item with id [oQnAT0C0sXsxpOaT] in parent Actor [GqqJiMadV2FwBP92]
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._addDisciplines (main.js:91:28)
    at async Steps2Foundry._import (main.js:234:13)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:6946 Foundry VTT | Created Item with id [Fmw3n7rvz4YSzea3] in parent Actor [GqqJiMadV2FwBP92]
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:361:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:362:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:361:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:362:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:361:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:362:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:361:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:362:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:361:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:362:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:361:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:362:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:361:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:362:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:361:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:362:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:361:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:362:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:361:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:362:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:361:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:362:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:361:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:362:34)
    at async Steps2Foundry._import (main.js:269:29)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
2commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:365:34)
    at async Steps2Foundry._import (main.js:270:28)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
3commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:368:34)
    at async Steps2Foundry._import (main.js:272:31)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
main.js:323 Steps2Foundry | Could not retrieve item "Traveler's Garb" from compendium "earthdawn-pg-compendium.goods"
commons.js:1703 Error: You are accessing earthdawn4eItem#data which has been migrated to earthdawn4eItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at earthdawn4eItem._logDataFieldMigration (commons.js:6631:14)
    at Object.get (commons.js:6595:18)
    at Steps2Foundry._getAllItemsFromComp (main.js:368:34)
    at async Steps2Foundry._import (main.js:272:31)
    at async Steps2Foundry.importJSON (main.js:66:9)

logCompatibilityWarning @ commons.js:1703
commons.js:6946 Foundry VTT | Created JournalEntry with id [TEr2JnwutZYBqSpf]
commons.js:6946 Foundry VTT | Created 18 Item documents in parent Actor [GqqJiMadV2FwBP92]
foundry.js:5099 Foundry VTT | Rendering earthdawn4ePCSheet
earthdawn-4e-PC-sheet.js:72 [EARTHDAWN] PC Data Object
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/earthdawn4e/templates/actors/sheets/pc-sheet.hbs
foundry.js:59187 Sorry, something went wrong. Have a look at the console (F12) or write a bug report.
fetch @ foundry.js:59187
``

**Comment by qrizzl** [comment]
Hi there,
sorry for the late reply. I had chance now to look at your issue. Unfortunately, this is no error but expected behavior. Currently, only Items that are part of the Player's Guide or the GM Guide compendia are supported. The shaman is part of Mystic Paths and therefore not supported yet.
I updated the code base to Foundry's V10 schema, so there are not as many warnings in the console. But this problem is not solvable yet.
There are plans to integrate all available compendia, but this might take a while. Until then, I hope you can still get some use out of the module.

Best, Chris
